"""Request/Response schemas module."""

from app.schemas.common import (
    BaseSchema,
    DeleteResponse,
    ErrorDetail,
    ErrorResponse,
    PaginatedResponse,
    SuccessResponse,
    TimestampSchema,
)
from app.schemas.product import (
    BulkProductCreate,
    BulkProductResponse,
    ProductCreate,
    ProductFilter,
    ProductResponse,
    ProductSummary,
    ProductUpdate,
)
from app.schemas.store import (
    BulkStoreCreate,
    BulkStoreResponse,
    StoreCreate,
    StoreFilter,
    StoreResponse,
    StoreSummary,
    StoreUpdate,
)
from app.schemas.sale import (
    BulkSaleCreate,
    BulkSaleResponse,
    SaleCreate,
    SaleFilter,
    SaleResponse,
    SaleSummary,
)
from app.schemas.optimization import (
    ConstraintSatisfaction,
    OptimizationConstraints,
    OptimizationRequest,
    OptimizationResponse,
    OptimizationResult,
    OptimizationSummary,
    ProductAllocation,
    SpaceAllocation,
)
from app.schemas.simulation import (
    AddSkuParams,
    ChangeFacingsParams,
    ChangePriceParams,
    DistributionStats,
    PercentileStats,
    RemoveSkuParams,
    SimulationConfig,
    SimulationRequest,
    SimulationResponse,
    SimulationResult,
    SimulationSummary,
)
from app.schemas.clustering import (
    ClusteringMethod,
    ClusteringRequest,
    ClusteringResponse,
    ClusteringResult,
    ClusteringSummary,
    ClusterProfile,
    ClusterRecommendation,
    PCACoordinate,
    StoreClusterAssignment,
)

__all__ = [
    # Common
    "BaseSchema",
    "TimestampSchema",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "DeleteResponse",
    # Product
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductSummary",
    "ProductFilter",
    "BulkProductCreate",
    "BulkProductResponse",
    # Store
    "StoreCreate",
    "StoreUpdate",
    "StoreResponse",
    "StoreSummary",
    "StoreFilter",
    "BulkStoreCreate",
    "BulkStoreResponse",
    # Sale
    "SaleCreate",
    "SaleResponse",
    "SaleSummary",
    "SaleFilter",
    "BulkSaleCreate",
    "BulkSaleResponse",
    # Optimization
    "OptimizationConstraints",
    "OptimizationRequest",
    "OptimizationResponse",
    "OptimizationResult",
    "OptimizationSummary",
    "ProductAllocation",
    "SpaceAllocation",
    "ConstraintSatisfaction",
    # Simulation
    "SimulationConfig",
    "SimulationRequest",
    "SimulationResponse",
    "SimulationResult",
    "SimulationSummary",
    "DistributionStats",
    "PercentileStats",
    "RemoveSkuParams",
    "AddSkuParams",
    "ChangeFacingsParams",
    "ChangePriceParams",
    # Clustering
    "ClusteringMethod",
    "ClusteringRequest",
    "ClusteringResponse",
    "ClusteringResult",
    "ClusteringSummary",
    "ClusterProfile",
    "ClusterRecommendation",
    "StoreClusterAssignment",
    "PCACoordinate",
]
