import type { Facility } from "@/components/map/facility"

export const facilityData: Facility[] = [
  {
    id: "1",
    name: "Rome Production",
    type: "Plant",
    status: "Operational",
    lat: 41.9028,
    lng: 12.4964,
    country: "Italy",
    address: "Via Roma 123, Rome, Italy",
    capacity: "10,000 units/day",
    efficiency: 92,
  },
  {
    id: "2",
    name: "Paris Distribution",
    type: "Distribution",
    status: "Operational",
    lat: 48.8566,
    lng: 2.3522,
    country: "France",
    address: "15 Rue de Paris, Paris, France",
    capacity: "25,000 units",
    efficiency: 88,
  },
  {
    id: "3",
    name: "Berlin Manufacturing",
    type: "Plant",
    status: "Warning",
    lat: 52.52,
    lng: 13.405,
    country: "Germany",
    address: "Berlinerstrasse 45, Berlin, Germany",
    capacity: "8,500 units/day",
    efficiency: 76,
  },
  {
    id: "4",
    name: "London Warehouse",
    type: "Distribution",
    status: "Operational",
    lat: 51.5074,
    lng: -0.1278,
    country: "UK",
    address: "10 London Road, London, UK",
    capacity: "30,000 units",
    efficiency: 94,
  },
  {
    id: "5",
    name: "Madrid Supplier",
    type: "Supplier",
    status: "Critical",
    lat: 40.4168,
    lng: -3.7038,
    country: "Spain",
    address: "Calle Madrid 78, Madrid, Spain",
    capacity: "5,000 units/day",
    efficiency: 65,
  },
  {
    id: "6",
    name: "Amsterdam Distribution",
    type: "Distribution",
    status: "Operational",
    lat: 52.3676,
    lng: 4.9041,
    country: "Netherlands",
    address: "Amsterdamstraat 22, Amsterdam, Netherlands",
    capacity: "15,000 units",
    efficiency: 91,
  },
  {
    id: "7",
    name: "New York Plant",
    type: "Plant",
    status: "Operational",
    lat: 40.7128,
    lng: -74.006,
    country: "USA",
    address: "123 Broadway, New York, USA",
    capacity: "12,000 units/day",
    efficiency: 89,
  },
  {
    id: "8",
    name: "Tokyo Production",
    type: "Plant",
    status: "Warning",
    lat: 35.6762,
    lng: 139.6503,
    country: "Japan",
    address: "1-1 Tokyo Street, Tokyo, Japan",
    capacity: "9,500 units/day",
    efficiency: 82,
  },
  {
    id: "9",
    name: "Sydney Warehouse",
    type: "Distribution",
    status: "Operational",
    lat: -33.8688,
    lng: 151.2093,
    country: "Australia",
    address: "45 Sydney Road, Sydney, Australia",
    capacity: "18,000 units",
    efficiency: 90,
  },
  {
    id: "10",
    name: "Shanghai Supplier",
    type: "Supplier",
    status: "Operational",
    lat: 31.2304,
    lng: 121.4737,
    country: "China",
    address: "100 Shanghai Street, Shanghai, China",
    capacity: "15,000 units/day",
    efficiency: 87,
  },
  {
    id: "11",
    name: "Mumbai Production",
    type: "Plant",
    status: "Critical",
    lat: 19.076,
    lng: 72.8777,
    country: "India",
    address: "Mumbai Industrial Zone, Mumbai, India",
    capacity: "7,000 units/day",
    efficiency: 62,
  },
  {
    id: "12",
    name: "São Paulo Distribution",
    type: "Distribution",
    status: "Warning",
    lat: -23.5505,
    lng: -46.6333,
    country: "Brazil",
    address: "Avenida São Paulo 123, São Paulo, Brazil",
    capacity: "20,000 units",
    efficiency: 78,
  },
  {
    id: "13",
    name: "Mexico City Supplier",
    type: "Supplier",
    status: "Operational",
    lat: 19.4326,
    lng: -99.1332,
    country: "Mexico",
    address: "Calle Mexico 45, Mexico City, Mexico",
    capacity: "6,000 units/day",
    efficiency: 85,
  },
  {
    id: "14",
    name: "Cairo Production",
    type: "Plant",
    status: "Warning",
    lat: 30.0444,
    lng: 31.2357,
    country: "Egypt",
    address: "Cairo Industrial Park, Cairo, Egypt",
    capacity: "5,500 units/day",
    efficiency: 75,
  },
  {
    id: "15",
    name: "Moscow Warehouse",
    type: "Distribution",
    status: "Operational",
    lat: 55.7558,
    lng: 37.6173,
    country: "Russia",
    address: "Moscow Logistics Center, Moscow, Russia",
    capacity: "22,000 units",
    efficiency: 88,
  },
]
