import type { NetworkData, WarehouseKpis } from "./types"

export const initialNetworkData: NetworkData = {
  plant: {
    name: "Manufacturing Plant",
  },
  centralWarehouse: {
    name: "Central Warehouse",
    orderQuantity: 200,
    safetyStock: 0,
    leadTime: 2,
    periods: [
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 150,
        scheduledReceipts: 0,
        netRequirements: 20,
        plannedReceipts: 0,
        endingInventory: 50,
        plannedOrder: 200,
      },
      {
        periodUsage: 20,
        grossRequirements: 20,
        beginningInventory: 50,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 30,
        plannedOrder: null,
      },
      {
        periodUsage: 50,
        grossRequirements: 50,
        beginningInventory: 30,
        scheduledReceipts: 0,
        netRequirements: 20,
        plannedReceipts: 200,
        endingInventory: 180,
        plannedOrder: null,
      },
      {
        periodUsage: 30,
        grossRequirements: 30,
        beginningInventory: 180,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 150,
        plannedOrder: null,
      },
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 150,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 50,
        plannedOrder: 200,
      },
      {
        periodUsage: 0,
        grossRequirements: 0,
        beginningInventory: 50,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 50,
        plannedOrder: null,
      },
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 50,
        scheduledReceipts: 0,
        netRequirements: 50,
        plannedReceipts: 200,
        endingInventory: 150,
        plannedOrder: null,
      },
      {
        periodUsage: 0,
        grossRequirements: 0,
        beginningInventory: 150,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 150,
        plannedOrder: null,
      },
    ],
  },
  regionalWarehouses: [
    {
      name: "Regional Warehouse One",
      orderQuantity: 50,
      safetyStock: 15,
      leadTime: 1,
      retailers: ["Retailer A", "Retailer B", "Retailer C"],
      periods: [
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 50,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 25,
          plannedOrder: 50,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 50,
          endingInventory: 50,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 50,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 25,
          plannedOrder: 50,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 50,
          endingInventory: 50,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 50,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 25,
          plannedOrder: 50,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 50,
          endingInventory: 50,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 50,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 25,
          plannedOrder: 50,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 50,
          endingInventory: 50,
          plannedOrder: null,
        },
      ],
    },
    {
      name: "Regional Warehouse Two",
      orderQuantity: 30,
      safetyStock: 10,
      leadTime: 1,
      retailers: ["Retailer D", "Retailer E", "Retailer F"],
      periods: [
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 30,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 10,
          plannedReceipts: 30,
          endingInventory: 30,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 30,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 20,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 30,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 20,
          plannedReceipts: 30,
          endingInventory: 20,
          plannedOrder: 30,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: 10,
          plannedReceipts: 30,
          endingInventory: 30,
          plannedOrder: null,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 30,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 30,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 20,
          plannedReceipts: 30,
          endingInventory: 20,
          plannedOrder: null,
        },
      ],
    },
    {
      name: "Regional Warehouse Three",
      orderQuantity: 20,
      safetyStock: 10,
      leadTime: 1,
      retailers: ["Retailer G", "Retailer H", "Retailer I"],
      periods: [
        {
          periodUsage: 5,
          grossRequirements: 15,
          beginningInventory: 15,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 20,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 20,
          endingInventory: 15,
          plannedOrder: 20,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 15,
          scheduledReceipts: 0,
          netRequirements: 5,
          plannedReceipts: 20,
          endingInventory: 25,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 15,
          plannedOrder: null,
        },
        {
          periodUsage: 0,
          grossRequirements: 10,
          beginningInventory: 15,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 15,
          plannedOrder: 20,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 15,
          scheduledReceipts: 0,
          netRequirements: 10,
          plannedReceipts: 20,
          endingInventory: 20,
          plannedOrder: null,
        },
        {
          periodUsage: 0,
          grossRequirements: 10,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 20,
          plannedOrder: 20,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: 5,
          plannedReceipts: 20,
          endingInventory: 25,
          plannedOrder: null,
        },
      ],
    },
  ],
}

export const initialKpis: WarehouseKpis = {
  "Central Warehouse": {
    serviceLevel: 98.5,
    inventoryTurnover: 3.2,
    averageInventory: 101.25,
    stockoutPeriods: 0,
    orderFrequency: 37.5, // percentage of periods with orders
  },
  "Regional Warehouse One": {
    serviceLevel: 100,
    inventoryTurnover: 4.0,
    averageInventory: 37.5,
    stockoutPeriods: 0,
    orderFrequency: 50,
  },
  "Regional Warehouse Two": {
    serviceLevel: 100,
    inventoryTurnover: 4.8,
    averageInventory: 18.75,
    stockoutPeriods: 0,
    orderFrequency: 50,
  },
  "Regional Warehouse Three": {
    serviceLevel: 100,
    inventoryTurnover: 3.5,
    averageInventory: 16.88,
    stockoutPeriods: 0,
    orderFrequency: 50,
  },
}
