import type { NetworkModel, OptimizationScenario } from "./types"

export const initialNetworkModel: NetworkModel = {
  costBreakdown: {
    totalCost: 146100,
    idFixedCost: 900,
    idTransport: 9800,
    idHandling: 6400,
    podTransport: 126000,
    podDeliveryProcessing: 3000,
  },
  intermediateDepots: [
    {
      id: "ID 1",
      varCost: 1.35,
      fixedCost: 1100,
      isOpen: false,
      flowFromCDC: 0,
      transportCost: 2.4,
    },
    {
      id: "ID 2",
      varCost: 1.6,
      fixedCost: 900,
      isOpen: true,
      flowFromCDC: 4000,
      transportCost: 2.45,
    },
  ],
  channelFlows: [
    {
      channelName: "Conv. Store",
      fromCDC: 4500,
      fromID1: 0,
      fromID2: 0,
      delivered: 4500,
      demanded: 4500,
      varCost: 0.5,
    },
    {
      channelName: "Retail Store",
      fromCDC: 15000,
      fromID1: 0,
      fromID2: 0,
      delivered: 15000,
      demanded: 15000,
      varCost: 0,
    },
    {
      channelName: "APS",
      fromCDC: 0,
      fromID1: 0,
      fromID2: 1000,
      delivered: 1000,
      demanded: 1000,
      varCost: 0.75,
    },
    {
      channelName: "Home",
      fromCDC: 0,
      fromID1: 0,
      fromID2: 3000,
      delivered: 3000,
      demanded: 3000,
      varCost: 0,
    },
  ],
  totalDemand: 23500,
  idsToOpen: {
    number: 1,
    min: 0,
    max: 2,
  },
  transportCosts: [
    {
      from: "CDC",
      convStore: 6.6,
      retailStore: 5.85,
      aps: 6.25,
      home: 8.15,
    },
    {
      from: "ID 1",
      convStore: 2.2,
      retailStore: 2.1,
      aps: 9999.0,
      home: 9999.0,
    },
    {
      from: "ID 2",
      convStore: 9999.0,
      retailStore: 9999.0,
      aps: 1.05,
      home: 3.4,
    },
  ],
  constraints: [
    {
      name: "ID 1 Capacity",
      value: 0,
      operator: "<=",
      limit: 20000,
    },
    {
      name: "ID 2 Capacity",
      value: 19500,
      operator: "<=",
      limit: 5000,
    },
    {
      name: "ID 1 Balance",
      value: 0,
      operator: "=",
      limit: 0,
    },
    {
      name: "ID 2 Balance",
      value: 0,
      operator: "=",
      limit: 0,
    },
  ],
}

export const initialScenarios: OptimizationScenario[] = [
  {
    id: "scenario-1",
    name: "Base Case",
    description: "Current network configuration with existing delivery options",
    createdAt: new Date(2025, 4, 20),
    totalCost: 146100,
    model: initialNetworkModel,
  },
  {
    id: "scenario-2",
    name: "Expanded APS",
    description: "Increased use of Automated Package Stations",
    createdAt: new Date(2025, 4, 21),
    totalCost: 142500,
    model: {
      ...initialNetworkModel,
      costBreakdown: {
        ...initialNetworkModel.costBreakdown,
        totalCost: 142500,
        podTransport: 122400,
      },
      channelFlows: [
        {
          channelName: "Conv. Store",
          fromCDC: 4500,
          fromID1: 0,
          fromID2: 0,
          delivered: 4500,
          demanded: 4500,
          varCost: 0.5,
        },
        {
          channelName: "Retail Store",
          fromCDC: 15000,
          fromID1: 0,
          fromID2: 0,
          delivered: 15000,
          demanded: 15000,
          varCost: 0,
        },
        {
          channelName: "APS",
          fromCDC: 0,
          fromID1: 0,
          fromID2: 2000,
          delivered: 2000,
          demanded: 2000,
          varCost: 0.75,
        },
        {
          channelName: "Home",
          fromCDC: 0,
          fromID1: 0,
          fromID2: 2000,
          delivered: 2000,
          demanded: 2000,
          varCost: 0,
        },
      ],
    },
  },
  {
    id: "scenario-3",
    name: "Both IDs Open",
    description: "Operating both intermediate depots",
    createdAt: new Date(2025, 4, 22),
    totalCost: 144800,
    model: {
      ...initialNetworkModel,
      costBreakdown: {
        ...initialNetworkModel.costBreakdown,
        totalCost: 144800,
        idFixedCost: 2000,
        idTransport: 8600,
      },
      intermediateDepots: [
        {
          id: "ID 1",
          varCost: 1.35,
          fixedCost: 1100,
          isOpen: true,
          flowFromCDC: 2000,
          transportCost: 2.4,
        },
        {
          id: "ID 2",
          varCost: 1.6,
          fixedCost: 900,
          isOpen: true,
          flowFromCDC: 2000,
          transportCost: 2.45,
        },
      ],
    },
  },
]
